services:
  app:
    container_name: dashboard-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: dashboard-backend
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - dashboard-network
  
  mysql:
    container_name: dashboard-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - dashboardVolume:/var/lib/mysql
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  redis:
    image: "redis:latest"
    container_name: dashboard_redis
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - dashboard-network

volumes:
  dashboardVolume:

networks:
  dashboard-network:
    driver: bridge
